FROM nvidia/cuda:12.2.0-runtime-ubuntu20.04

LABEL description="Container for Llama2 chatbot backend."

WORKDIR /app

COPY ./backend_requirements.txt /app/

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/London


RUN  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get update && apt-get upgrade -y && \
    apt-get install -y python3 python3-pip git libsqlite3-dev curl unzip gcc g++ make cmake

RUN pip install --upgrade pip && \
    pip install git+https://github.com/huggingface/transformers \
    pip install pypdf \
    pip install --no-cache-dir --upgrade -r backend_requirements.txt

COPY ./backendQA_demo.py /app/
COPY ./data_pdf/ /app/data_pdf/

EXPOSE 5000

CMD [ "uvicorn","backendQA_demo:app","--host","0.0.0.0","--port","5000","--reload"]