wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.7
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.34.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700742448.275834
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 55
      - 86
      3:
      - 23
      4: 3.10.7
      5: 0.15.12
      6: 4.34.0
      8:
      - 5
      13: linux-x86_64
